[board]
id          = "esp32"
name        = "ESP32 Dev Module"
fqbn        = "esp32:esp32:esp32"
variant     = "esp32"
flash_kb    = 4096
ram_kb      = 520
description = "ESP32 Dev Module — Xtensa LX6 dual-core, WiFi, BT, 4MB flash"
author      = "tsuki-team"
version     = "1.0.0"

[toolchain]
type        = "esp32"
variant     = "esp32"

[defines]
values = ["ARDUINO_ESP32_DEV", "ARDUINO_ARCH_ESP32", "ESP32"]
