// src/lib/themes.ts

export interface IdeTheme {
  id: string
  name: string
  base: 'dark' | 'light'
  preview: { bg: string; border: string; fg: string; accent: string }
  vars: Record<string, string>
}

export interface SyntaxTheme {
  id: string
  name: string
  swatches: string[]   // preview colors [kw, str, num, fn, com]
  vars: Record<string, string>
}

export const IDE_THEMES: IdeTheme[] = [
  {
    id: 'dark',
    name: 'Dark',
    base: 'dark',
    preview: { bg: '#111111', border: '#242424', fg: '#ededed', accent: '#ededed' },
    vars: {
      '--surface':        '#0a0a0a',
      '--surface-1':      '#111111',
      '--surface-2':      '#171717',
      '--surface-3':      '#1f1f1f',
      '--surface-4':      '#282828',
      '--fg':             '#ededed',
      '--fg-muted':       '#8c8c8c',
      '--fg-faint':       '#484848',
      '--border':         '#242424',
      '--border-subtle':  '#1c1c1c',
      '--accent':         '#ededed',
      '--accent-inv':     '#0a0a0a',
      '--active-border':  '#555',
      '--hover':          'rgba(255,255,255,0.04)',
      '--active':         'rgba(255,255,255,0.08)',
      '--ok':             '#22c55e',
      '--err':            '#ef4444',
      '--warn':           '#f59e0b',
      '--info':           '#93c5fd',
      '--chrome-bg':      '#0e0f10',
      '--chrome-border':  '#1e2022',
      '--chrome-sep':     '#242628',
      '--chrome-fg':      '#c8ccd0',
      '--chrome-fg-muted':'#6b6f72',
      '--chrome-input':   '#181a1b',
      '--chrome-group':   '#141618',
    },
  },
  {
    id: 'light',
    name: 'Light',
    base: 'light',
    preview: { bg: '#fafafa', border: '#e8e8e8', fg: '#111111', accent: '#111111' },
    vars: {
      '--surface':        '#ffffff',
      '--surface-1':      '#fafafa',
      '--surface-2':      '#f5f5f5',
      '--surface-3':      '#efefef',
      '--surface-4':      '#e8e8e8',
      '--fg':             '#111111',
      '--fg-muted':       '#737373',
      '--fg-faint':       '#c4c4c4',
      '--border':         '#e8e8e8',
      '--border-subtle':  '#f0f0f0',
      '--accent':         '#111111',
      '--accent-inv':     '#ffffff',
      '--active-border':  '#999',
      '--hover':          'rgba(0,0,0,0.03)',
      '--active':         'rgba(0,0,0,0.06)',
      '--ok':             '#16a34a',
      '--err':            '#dc2626',
      '--warn':           '#d97706',
      '--info':           '#3b82f6',
      '--chrome-bg':      '#f0f0f0',
      '--chrome-border':  '#d8d8d8',
      '--chrome-sep':     '#d0d0d0',
      '--chrome-fg':      '#1a1a1a',
      '--chrome-fg-muted':'#666666',
      '--chrome-input':   '#e8e8e8',
      '--chrome-group':   '#e0e0e0',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    base: 'dark',
    preview: { bg: '#0c0c1a', border: '#1e1e3a', fg: '#cdd6f4', accent: '#89b4fa' },
    vars: {
      '--surface':        '#070710',
      '--surface-1':      '#0c0c1a',
      '--surface-2':      '#111122',
      '--surface-3':      '#181830',
      '--surface-4':      '#1f1f3a',
      '--fg':             '#cdd6f4',
      '--fg-muted':       '#a6adc8',
      '--fg-faint':       '#585b70',
      '--border':         '#1e1e3a',
      '--border-subtle':  '#14142a',
      '--active':         '#1e1e3a',
      '--hover':          '#181830',
      '--ok':             '#a6e3a1',
      '--warn':           '#f9e2af',
      '--err':            '#f38ba8',
      '--info':           '#89b4fa',
      '--accent-inv':     '#070710',
    },
  },
  {
    id: 'warm-dark',
    name: 'Warm Dark',
    base: 'dark',
    preview: { bg: '#1a1816', border: '#2e2c24', fg: '#e8e0d0', accent: '#e5ad4c' },
    vars: {
      '--surface':        '#100f0e',
      '--surface-1':      '#1a1816',
      '--surface-2':      '#22201c',
      '--surface-3':      '#2a2822',
      '--surface-4':      '#333028',
      '--fg':             '#e8e0d0',
      '--fg-muted':       '#b8ae9e',
      '--fg-faint':       '#5c5648',
      '--border':         '#2e2c24',
      '--border-subtle':  '#22201c',
      '--active':         '#2a2822',
      '--hover':          '#242218',
      '--ok':             '#7fc590',
      '--warn':           '#e5ad4c',
      '--err':            '#e06c75',
      '--info':           '#7ab0d4',
      '--accent-inv':     '#100f0e',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized',
    base: 'dark',
    preview: { bg: '#073642', border: '#0a3d4a', fg: '#93a1a1', accent: '#268bd2' },
    vars: {
      '--surface':        '#002b36',
      '--surface-1':      '#073642',
      '--surface-2':      '#0a3d4a',
      '--surface-3':      '#0d4855',
      '--surface-4':      '#12505f',
      '--fg':             '#93a1a1',
      '--fg-muted':       '#657b83',
      '--fg-faint':       '#4a5f66',
      '--border':         '#0a3d4a',
      '--border-subtle':  '#073642',
      '--active':         '#073642',
      '--hover':          '#0a3d4a',
      '--ok':             '#859900',
      '--warn':           '#b58900',
      '--err':            '#dc322f',
      '--info':           '#268bd2',
      '--accent-inv':     '#002b36',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    base: 'dark',
    preview: { bg: '#0a0a0a', border: '#555555', fg: '#ffffff', accent: '#33aaff' },
    vars: {
      '--surface':        '#000000',
      '--surface-1':      '#0a0a0a',
      '--surface-2':      '#111111',
      '--surface-3':      '#1a1a1a',
      '--surface-4':      '#222222',
      '--fg':             '#ffffff',
      '--fg-muted':       '#cccccc',
      '--fg-faint':       '#888888',
      '--border':         '#555555',
      '--border-subtle':  '#333333',
      '--active':         '#1a1a1a',
      '--hover':          '#1a1a1a',
      '--ok':             '#00ff88',
      '--warn':           '#ffff00',
      '--err':            '#ff3333',
      '--info':           '#33aaff',
      '--accent-inv':     '#000000',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    base: 'dark',
    preview: { bg: '#1e1e2e', border: '#313244', fg: '#cdd6f4', accent: '#cba6f7' },
    vars: {
      '--surface':        '#181825',
      '--surface-1':      '#1e1e2e',
      '--surface-2':      '#24243a',
      '--surface-3':      '#313244',
      '--surface-4':      '#3a3a58',
      '--fg':             '#cdd6f4',
      '--fg-muted':       '#bac2de',
      '--fg-faint':       '#6c7086',
      '--border':         '#313244',
      '--border-subtle':  '#262637',
      '--active':         '#313244',
      '--hover':          '#292940',
      '--ok':             '#a6e3a1',
      '--warn':           '#f9e2af',
      '--err':            '#f38ba8',
      '--info':           '#89b4fa',
      '--accent-inv':     '#181825',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    base: 'light',
    preview: { bg: '#eff1f5', border: '#ccd0da', fg: '#4c4f69', accent: '#8839ef' },
    vars: {
      '--surface':        '#ffffff',
      '--surface-1':      '#eff1f5',
      '--surface-2':      '#e6e9ef',
      '--surface-3':      '#dce0e8',
      '--surface-4':      '#ccd0da',
      '--fg':             '#4c4f69',
      '--fg-muted':       '#6c6f85',
      '--fg-faint':       '#9ca0b0',
      '--border':         '#ccd0da',
      '--border-subtle':  '#dce0e8',
      '--active':         '#dce0e8',
      '--hover':          '#e6e9ef',
      '--ok':             '#40a02b',
      '--warn':           '#df8e1d',
      '--err':            '#d20f39',
      '--info':           '#1e66f5',
      '--accent-inv':     '#ffffff',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    base: 'dark',
    preview: { bg: '#1a1b26', border: '#292e42', fg: '#a9b1d6', accent: '#7aa2f7' },
    vars: {
      '--surface':        '#13141f',
      '--surface-1':      '#1a1b26',
      '--surface-2':      '#1f2335',
      '--surface-3':      '#24283b',
      '--surface-4':      '#292e42',
      '--fg':             '#a9b1d6',
      '--fg-muted':       '#9aa5ce',
      '--fg-faint':       '#565f89',
      '--border':         '#292e42',
      '--border-subtle':  '#1f2335',
      '--active':         '#292e42',
      '--hover':          '#222436',
      '--ok':             '#9ece6a',
      '--warn':           '#e0af68',
      '--err':            '#f7768e',
      '--info':           '#7aa2f7',
      '--accent-inv':     '#13141f',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    base: 'dark',
    preview: { bg: '#282a36', border: '#44475a', fg: '#f8f8f2', accent: '#bd93f9' },
    vars: {
      '--surface':        '#1e1f29',
      '--surface-1':      '#282a36',
      '--surface-2':      '#2d2f3f',
      '--surface-3':      '#343746',
      '--surface-4':      '#44475a',
      '--fg':             '#f8f8f2',
      '--fg-muted':       '#cfcfcf',
      '--fg-faint':       '#6272a4',
      '--border':         '#44475a',
      '--border-subtle':  '#343746',
      '--active':         '#44475a',
      '--hover':          '#3a3c4e',
      '--ok':             '#50fa7b',
      '--warn':           '#f1fa8c',
      '--err':            '#ff5555',
      '--info':           '#8be9fd',
      '--accent-inv':     '#1e1f29',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    base: 'dark',
    preview: { bg: '#21252b', border: '#3a3f4b', fg: '#abb2bf', accent: '#61afef' },
    vars: {
      '--surface':        '#1b1f23',
      '--surface-1':      '#21252b',
      '--surface-2':      '#282c34',
      '--surface-3':      '#2c313a',
      '--surface-4':      '#3a3f4b',
      '--fg':             '#abb2bf',
      '--fg-muted':       '#9da5b4',
      '--fg-faint':       '#4b5263',
      '--border':         '#3a3f4b',
      '--border-subtle':  '#2c313a',
      '--active':         '#2c313a',
      '--hover':          '#282c34',
      '--ok':             '#98c379',
      '--warn':           '#e5c07b',
      '--err':            '#e06c75',
      '--info':           '#61afef',
      '--accent-inv':     '#1b1f23',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    base: 'dark',
    preview: { bg: '#191724', border: '#26233a', fg: '#e0def4', accent: '#c4a7e7' },
    vars: {
      '--surface':        '#111019',
      '--surface-1':      '#191724',
      '--surface-2':      '#1f1d2e',
      '--surface-3':      '#26233a',
      '--surface-4':      '#2e2b3d',
      '--fg':             '#e0def4',
      '--fg-muted':       '#908caa',
      '--fg-faint':       '#524f67',
      '--border':         '#26233a',
      '--border-subtle':  '#1f1d2e',
      '--active':         '#26233a',
      '--hover':          '#232136',
      '--ok':             '#9ccfd8',
      '--warn':           '#f6c177',
      '--err':            '#eb6f92',
      '--info':           '#9ccfd8',
      '--accent-inv':     '#111019',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    base: 'dark',
    preview: { bg: '#282828', border: '#3c3836', fg: '#ebdbb2', accent: '#fabd2f' },
    vars: {
      '--surface':        '#1d2021',
      '--surface-1':      '#282828',
      '--surface-2':      '#32302f',
      '--surface-3':      '#3c3836',
      '--surface-4':      '#504945',
      '--fg':             '#ebdbb2',
      '--fg-muted':       '#d5c4a1',
      '--fg-faint':       '#7c6f64',
      '--border':         '#3c3836',
      '--border-subtle':  '#32302f',
      '--active':         '#3c3836',
      '--hover':          '#32302f',
      '--ok':             '#b8bb26',
      '--warn':           '#fabd2f',
      '--err':            '#fb4934',
      '--info':           '#83a598',
      '--accent-inv':     '#1d2021',
    },
  },
]

export const SYNTAX_THEMES: SyntaxTheme[] = [
  {
    id: 'material',
    name: 'Material',
    swatches: ['#c792ea', '#c3e88d', '#f78c6c', '#82aaff', '#546e7a'],
    vars: {
      '--syn-kw':  '#c792ea',
      '--syn-typ': '#82aaff',
      '--syn-str': '#c3e88d',
      '--syn-num': '#f78c6c',
      '--syn-com': '#546e7a',
      '--syn-fn':  '#82aaff',
      '--syn-pkg': '#ffcb6b',
      '--syn-op':  '#89ddff',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    swatches: ['#f92672', '#e6db74', '#ae81ff', '#a6e22e', '#75715e'],
    vars: {
      '--syn-kw':  '#f92672',
      '--syn-typ': '#66d9e8',
      '--syn-str': '#e6db74',
      '--syn-num': '#ae81ff',
      '--syn-com': '#75715e',
      '--syn-fn':  '#a6e22e',
      '--syn-pkg': '#66d9e8',
      '--syn-op':  '#f8f8f2',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    swatches: ['#81a1c1', '#a3be8c', '#b48ead', '#88c0d0', '#616e88'],
    vars: {
      '--syn-kw':  '#81a1c1',
      '--syn-typ': '#8fbcbb',
      '--syn-str': '#a3be8c',
      '--syn-num': '#b48ead',
      '--syn-com': '#616e88',
      '--syn-fn':  '#88c0d0',
      '--syn-pkg': '#ebcb8b',
      '--syn-op':  '#eceff4',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    swatches: ['#ff7b72', '#a5d6ff', '#79c0ff', '#d2a8ff', '#8b949e'],
    vars: {
      '--syn-kw':  '#ff7b72',
      '--syn-typ': '#79c0ff',
      '--syn-str': '#a5d6ff',
      '--syn-num': '#79c0ff',
      '--syn-com': '#8b949e',
      '--syn-fn':  '#d2a8ff',
      '--syn-pkg': '#ffa657',
      '--syn-op':  '#c9d1d9',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    swatches: ['#859900', '#2aa198', '#d33682', '#268bd2', '#93a1a1'],
    vars: {
      '--syn-kw':  '#859900',
      '--syn-typ': '#268bd2',
      '--syn-str': '#2aa198',
      '--syn-num': '#d33682',
      '--syn-com': '#93a1a1',
      '--syn-fn':  '#268bd2',
      '--syn-pkg': '#b58900',
      '--syn-op':  '#657b83',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    swatches: ['#ff79c6', '#f1fa8c', '#bd93f9', '#50fa7b', '#6272a4'],
    vars: {
      '--syn-kw':  '#ff79c6',
      '--syn-typ': '#8be9fd',
      '--syn-str': '#f1fa8c',
      '--syn-num': '#bd93f9',
      '--syn-com': '#6272a4',
      '--syn-fn':  '#50fa7b',
      '--syn-pkg': '#ffb86c',
      '--syn-op':  '#ff79c6',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    swatches: ['#cba6f7', '#a6e3a1', '#fab387', '#89b4fa', '#585b70'],
    vars: {
      '--syn-kw':  '#cba6f7',
      '--syn-typ': '#89dceb',
      '--syn-str': '#a6e3a1',
      '--syn-num': '#fab387',
      '--syn-com': '#585b70',
      '--syn-fn':  '#89b4fa',
      '--syn-pkg': '#f9e2af',
      '--syn-op':  '#94e2d5',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    swatches: ['#9d7cd8', '#9ece6a', '#ff9e64', '#7aa2f7', '#565f89'],
    vars: {
      '--syn-kw':  '#9d7cd8',
      '--syn-typ': '#2ac3de',
      '--syn-str': '#9ece6a',
      '--syn-num': '#ff9e64',
      '--syn-com': '#565f89',
      '--syn-fn':  '#7aa2f7',
      '--syn-pkg': '#e0af68',
      '--syn-op':  '#89ddff',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    swatches: ['#c678dd', '#98c379', '#d19a66', '#61afef', '#5c6370'],
    vars: {
      '--syn-kw':  '#c678dd',
      '--syn-typ': '#e5c07b',
      '--syn-str': '#98c379',
      '--syn-num': '#d19a66',
      '--syn-com': '#5c6370',
      '--syn-fn':  '#61afef',
      '--syn-pkg': '#e06c75',
      '--syn-op':  '#56b6c2',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    swatches: ['#fb4934', '#b8bb26', '#d3869b', '#83a598', '#928374'],
    vars: {
      '--syn-kw':  '#fb4934',
      '--syn-typ': '#fabd2f',
      '--syn-str': '#b8bb26',
      '--syn-num': '#d3869b',
      '--syn-com': '#928374',
      '--syn-fn':  '#83a598',
      '--syn-pkg': '#fe8019',
      '--syn-op':  '#8ec07c',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    swatches: ['#cf222e', '#0a3069', '#0550ae', '#8250df', '#6e7781'],
    vars: {
      '--syn-kw':  '#cf222e',
      '--syn-typ': '#0550ae',
      '--syn-str': '#0a3069',
      '--syn-num': '#0550ae',
      '--syn-com': '#6e7781',
      '--syn-fn':  '#8250df',
      '--syn-pkg': '#953800',
      '--syn-op':  '#24292f',
    },
  },
]

/** Applies a full theme to the document root — safe to call on every settings change. */
export function applyTheme(ideThemeId: string, syntaxThemeId: string): void {
  if (typeof window === 'undefined') return
  const theme  = IDE_THEMES.find(t => t.id === ideThemeId)      ?? IDE_THEMES[0]
  const syntax = SYNTAX_THEMES.find(s => s.id === syntaxThemeId) ?? SYNTAX_THEMES[0]
  const root   = document.documentElement
  // Keep dark/light class in sync for any remaining globals.css rules
  root.classList.remove('dark', 'light')
  root.classList.add(theme.base)
  // Inline style properties win over every stylesheet rule
  for (const [k, v] of Object.entries({ ...theme.vars, ...syntax.vars })) {
    root.style.setProperty(k, v)
  }
}

export function applyUiScale(scale: number): void {
  if (typeof window === 'undefined') return
  // Scales all rem-based Tailwind classes; editor px fontSize is unaffected
  document.documentElement.style.fontSize = scale === 1 ? '' : `${scale * 100}%`
}

export function applyFontRendering(mode: 'auto' | 'crisp' | 'smooth' | 'subpixel'): void {
  if (typeof window === 'undefined') return
  const el = document.documentElement
  const smoothing: Record<string, string> = {
    auto:     '',
    crisp:    'none',
    smooth:   'antialiased',
    subpixel: 'subpixel-antialiased',
  }
  const s = el.style as unknown as Record<string, string>
  s['webkitFontSmoothing'] = smoothing[mode]
  s['MozOsxFontSmoothing'] = mode === 'smooth' ? 'grayscale' : mode === 'subpixel' ? 'auto' : ''
}

export function applyCompactMode(compact: boolean): void {
  document.documentElement.setAttribute('data-compact', compact ? 'true' : 'false')
}