// ─────────────────────────────────────────────────────────────────────────────
//  tsuki :: transpiler  (updated)
//  Now accepts a pre-built Runtime so external library packages are
//  already registered before code-gen begins.
// ─────────────────────────────────────────────────────────────────────────────

pub mod config;
pub use config::TranspileConfig;

use std::collections::{HashMap, HashSet};

use crate::error::{TsukiError, Result};
use crate::parser::ast::*;
use crate::runtime::Runtime;

// ─────────────────────────────────────────────────────────────────────────────

pub struct Transpiler {
    cfg:          TranspileConfig,
    rt:           Runtime,
    indent:       usize,
    includes:     HashSet<String>,
    pkg_map:      HashMap<String, String>,
    /// Maps local variable names → canonical package name for instance-method dispatch.
    var_types:    HashMap<String, String>,
    /// Source length hint for pre-sizing the output buffer in `generate()`.
    src_len_hint: usize,
}

impl Transpiler {
    /// Create with default (built-in only) runtime.
    pub fn new(cfg: TranspileConfig) -> Self {
        Self::with_runtime(cfg, Runtime::new())
    }

    /// Create with a pre-built runtime (may contain external libs).
    pub fn with_runtime(cfg: TranspileConfig, rt: Runtime) -> Self {
        Self {
            cfg,
            rt,
            indent:       0,
            includes:     HashSet::new(),
            pkg_map:      HashMap::new(),
            var_types:    HashMap::new(),
            src_len_hint: 0,
        }
    }

    pub fn generate(&mut self, prog: &Program) -> Result<String> {
        self.resolve_imports(&prog.imports);
        self.includes.insert("Arduino.h".into());

        // Partition declarations once — borrows prog.decls as refs
        let mut structs:   Vec<&Decl> = Vec::new();
        let mut typedefs:  Vec<&Decl> = Vec::new();
        let mut constants: Vec<&Decl> = Vec::new();
        let mut globals:   Vec<&Decl> = Vec::new();
        let mut funcs:     Vec<&Decl> = Vec::new();

        for d in &prog.decls {
            match d {
                Decl::StructDef { .. } => structs.push(d),
                Decl::TypeDef   { .. } => typedefs.push(d),
                Decl::Const     { .. } => constants.push(d),
                Decl::Var       { .. } => globals.push(d),
                Decl::Func      { .. } => funcs.push(d),
            }
        }

        // Pre-allocate output buffer.
        // Average C++ output is ~4× the source size for Arduino sketches.
        let estimated = (self.src_len_hint).max(512) * 4;
        let mut out = String::with_capacity(estimated);

        // Header comment
        use std::fmt::Write as W;
        let _ = write!(out,
            "// Generated by tsuki v{} — do not edit manually.\n// Source package: {}\n\n",
            env!("CARGO_PKG_VERSION"), &prog.package
        );

        // Sorted #includes — sort the Vec (already cloned), avoid temp alloc
        let mut incs: Vec<&String> = self.includes.iter().collect();
        incs.sort_unstable();
        for i in incs { let _ = write!(out, "#include <{}>\n", i); }
        out.push('\n');

        for td in &typedefs  { out.push_str(&self.emit_typedef(td)?); }
        if !typedefs.is_empty() { out.push('\n'); }

        for s in &structs    { out.push_str(&self.emit_struct(s)?); }
        if !structs.is_empty() { out.push('\n'); }

        // Clone constants/globals to release the shared borrow on prog.decls
        // so emit_const/emit_global can take &mut self.
        let constants_owned: Vec<Decl> = constants.iter().map(|d| (*d).clone()).collect();
        for c in &constants_owned { out.push_str(&self.emit_const(c)?); }
        if !constants_owned.is_empty() { out.push('\n'); }

        let globals_owned: Vec<Decl> = globals.iter().map(|d| (*d).clone()).collect();
        for g in &globals_owned { out.push_str(&self.emit_global(g)?); }
        if !globals_owned.is_empty() { out.push('\n'); }

        // Forward declarations (non-setup/loop user functions)
        for f in &funcs {
            if let Decl::Func { name, sig, recv: None, .. } = f {
                if name != "setup" && name != "loop" {
                    out.push_str(&self.emit_func_fwd(name, sig)?);
                }
            }
        }
        out.push('\n');

        let mut saw_setup = false;
        let mut saw_loop  = false;
        for f in &funcs {
            if let Decl::Func { name, .. } = f {
                if name == "setup" || name == "main" { saw_setup = true; }
                if name == "loop"  { saw_loop  = true; }
            }
            out.push_str(&self.emit_func(f)?);
            out.push('\n');
        }

        if !saw_setup { out.push_str("void setup() {}\n\n"); }
        if !saw_loop  { out.push_str("void loop()  {}\n\n"); }

        Ok(out)
    }

    /// Hint: set the source length so `generate()` can pre-size the output buffer.
    #[allow(dead_code)]
    pub fn set_src_len_hint(&mut self, n: usize) { self.src_len_hint = n; }

    // ── Imports ───────────────────────────────────────────────────────────────

    fn resolve_imports(&mut self, imports: &[Import]) {
        for imp in imports {
            let raw_path: String = imp.path.split('/').last()
                .unwrap_or(&imp.path).to_owned();

            // Normalise hyphenated package names to a valid C identifier.
            // e.g. "tsuki-webkit" → "tsuki_webkit"
            let canon: String = raw_path.replace('-', "_");

            // The Go alias: if user wrote `import tw "tsuki-webkit"` use "tw",
            // otherwise derive from the last path segment keeping hyphens as
            // they appear in Go source so the parser can look them up.
            let alias = if let Some(a) = &imp.alias {
                a.clone()
            } else {
                raw_path.clone()   // keep original (may contain hyphens)
            };

            // Also register the underscore-normalised alias so both
            // `tsuki-webkit.X` and `tsuki_webkit.X` resolve correctly.
            self.pkg_map.insert(alias.clone(), canon.clone());
            if alias != canon {
                self.pkg_map.insert(canon.clone(), canon.clone());
            }

            // ── tsuki-webkit: inject the generated header instead of a pkg lookup ──
            if canon == "tsuki_webkit" || raw_path == "tsuki-webkit" {
                self.includes.insert("tsuki_webkit_gen.h".into());
                // webkit is a C++ lib injected by tsuki-flash — no further
                // runtime lookup needed.
                continue;
            }

            if let Some(pkg) = self.rt.pkg(&canon) {
                if let Some(h) = &pkg.header {
                    self.includes.insert(h.clone());
                }
            }
        }
    }

    fn push_indent(&mut self) { self.indent += 1; }

    /// Return indentation string. Uses a static lookup to avoid allocation for common depths.
    fn pad(&self) -> &'static str {
        // Pre-computed indent levels (up to 8 levels = 32 spaces, covers all real code)
        const PADS: [&str; 9] = [
            "",
            "    ",
            "        ",
            "            ",
            "                ",
            "                    ",
            "                        ",
            "                            ",
            "                                ",
        ];
        PADS.get(self.indent).copied().unwrap_or("                                ")
    }
    fn pop_indent(&mut self)  { if self.indent > 0 { self.indent -= 1; } }

    fn emit_typedef(&self, d: &Decl) -> Result<String> {
        if let Decl::TypeDef { name, ty, .. } = d {
            Ok(format!("typedef {} {};\n", ty.to_cpp(), name))
        } else { Ok(String::new()) }
    }

    fn emit_struct(&self, d: &Decl) -> Result<String> {
        if let Decl::StructDef { name, fields, .. } = d {
            let mut s = format!("struct {} {{\n", name);
            for f in fields {
                let fname = f.name.as_deref().unwrap_or("_");
                s += &format!("    {} {};\n", f.ty.to_cpp(), fname);
            }
            s += "};\n";
            Ok(s)
        } else { Ok(String::new()) }
    }

    fn emit_const(&mut self, d: &Decl) -> Result<String> {
        if let Decl::Const { name, ty, val, .. } = d {
            // ── tsuki-webkit: const app = tsuki_webkit.ApiInit() ─────────────
            if let Expr::Call { func, .. } = val {
                if let Expr::Select { expr, .. } = func.as_ref() {
                    if let Expr::Ident { name: pkg_alias, .. } = expr.as_ref() {
                        if let Some(canon) = self.pkg_map.get(pkg_alias.as_str()).cloned() {
                            if canon == "tsuki_webkit" {
                                self.var_types.insert(name.clone(), canon);
                                // Emit a zero-size tag struct + static instance.
                                // The actual webkit C++ is injected by tsuki-flash
                                // via webkit_setup_routes() / webkit_tick().
                                return Ok(format!(
                                    "struct WebkitHandle {{}};\nstatic WebkitHandle {};\n",
                                    name
                                ));
                            }
                        }
                    }
                }
            }
            let v = self.emit_expr(val)?;
            let t = ty.as_ref().map(|t| t.to_cpp()).unwrap_or_else(|| "auto".into());
            Ok(format!("const {} {} = {};\n", t, name, v))
        } else { Ok(String::new()) }
    }

    fn emit_global(&mut self, d: &Decl) -> Result<String> {
        if let Decl::Var { name, ty, init, .. } = d {
            // ── tsuki-webkit: detect  `const app = tsuki_webkit.ApiInit()` ────
            // The init expression is a call like `tsuki_webkit.ApiInit()`.
            // After the pre-processor the alias is already `tsuki_webkit`.
            // We register `app` → `tsuki_webkit` so that `app.setup()` and
            // `app.tick()` resolve correctly, and suppress the C++ initialiser
            // (webkit_setup_routes is called explicitly from setup()).
            if let Some(init_expr) = init {
                if let Expr::Call { func, .. } = init_expr {
                    if let Expr::Select { expr, field: _, .. } = func.as_ref() {
                        if let Expr::Ident { name: pkg_alias, .. } = expr.as_ref() {
                            if let Some(canon) = self.pkg_map.get(pkg_alias.as_str()).cloned() {
                                if canon == "tsuki_webkit" {
                                    // Register the variable so instance calls work
                                    self.var_types.insert(name.clone(), canon.clone());
                                    // Emit a WebkitHandle struct — zero-size, just a tag
                                    return Ok(format!(
                                        "struct WebkitHandle {{}};\nWebkitHandle {};\n",
                                        name
                                    ));
                                }
                            }
                        }
                    }
                }
            }

            // Track variable → package for instance-method dispatch
            // ── Fast path: explicit type annotation (e.g. var sensor dht.DHT = ...) ──
            if let Some(Type::Named(type_name)) = ty {
                let pkg_part = type_name.split('.').next().unwrap_or("");
                if let Some(canon) = self.pkg_map.get(pkg_part).cloned() {
                    self.var_types.insert(name.clone(), canon.clone());
                    // If this package declares a C++ class, emit as pointer
                    // (many Arduino libs lack a default constructor).
                    if let Some(pkg) = self.rt.pkg(&canon) {
                        if let Some(class) = pkg.cpp_class.clone() {
                            // Stack allocation: emit ClassName varname(args) idiomatically.
                            if let Some(e) = init {
                                let val = self.emit_expr(e)?;
                                let ctor_prefix = format!("{}(", class);
                                if val.starts_with(&ctor_prefix) && val.ends_with(')') {
                                    let inner = &val[ctor_prefix.len()..val.len()-1];
                                    return Ok(format!("{} {}({});\n", class, name, inner));
                                } else {
                                    return Ok(format!("{} {} = {};\n", class, name, val));
                                }
                            } else {
                                return Ok(format!("{} {};\n", class, name));
                            }
                        }
                    }
                }
            }
            // ── Inferred path: no annotation but init is pkg.Constructor(...) ──
            // e.g. var sensor = dht.New(pin, dht.DHT22)
            // Mirror the ShortDecl logic so var_types is populated and cpp_class
            // constructor syntax is applied consistently.
            if ty.is_none() {
                if let Some(init_expr) = init {
                    if let Expr::Call { func, .. } = init_expr {
                        if let Expr::Select { expr: pkg_expr, .. } = func.as_ref() {
                            if let Expr::Ident { name: pkg_alias, .. } = pkg_expr.as_ref() {
                                if let Some(canon) = self.pkg_map.get(pkg_alias.as_str()).cloned() {
                                    self.var_types.insert(name.clone(), canon.clone());
                                    if let Some(pkg) = self.rt.pkg(&canon) {
                                        if let Some(class) = pkg.cpp_class.clone() {
                                            let val = self.emit_expr(init_expr)?;
                                            let ctor_prefix = format!("{}(", class);
                                            if val.starts_with(&ctor_prefix) && val.ends_with(')') {
                                                let inner = &val[ctor_prefix.len()..val.len()-1];
                                                return Ok(format!("{} {}({});\n", class, name, inner));
                                            } else {
                                                return Ok(format!("{} {} = {};\n", class, name, val));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let t    = ty.as_ref().map(|t| t.to_cpp()).unwrap_or_else(|| "auto".into());
            let init = init.as_ref().map(|e| self.emit_expr(e)).transpose()?
                .map(|s| format!(" = {}", s)).unwrap_or_default();
            Ok(format!("{} {}{};
", t, name, init))
        } else { Ok(String::new()) }
    }

    fn emit_func_fwd(&self, name: &str, sig: &FuncSig) -> Result<String> {
        // Go's main() becomes setup() — don't forward-declare it under "main"
        let cpp_name = if name == "main" { "setup" } else { name };
        Ok(format!("{} {}({});\n", ret_type(sig), cpp_name, params_str(sig)))
    }

    fn emit_func(&mut self, d: &Decl) -> Result<String> {
        if let Decl::Func { name, recv, sig, body, .. } = d {
            let mut buf = String::with_capacity(256);
            // Return type
            ret_type_into(sig, &mut buf);
            buf.push(' ');
            // Receiver-qualified or plain name
            if let Some(r) = recv {
                let type_name: std::borrow::Cow<str> = match &r.ty {
                    Type::Ptr(inner) => match inner.as_ref() {
                        Type::Named(n) => std::borrow::Cow::Borrowed(n.as_str()),
                        t              => std::borrow::Cow::Owned(t.to_cpp()),
                    },
                    Type::Named(n) => std::borrow::Cow::Borrowed(n.as_str()),
                    t              => std::borrow::Cow::Owned(t.to_cpp()),
                };
                buf.push_str(&type_name);
                buf.push_str("::");
                buf.push_str(name);
            } else {
                buf.push_str(if name == "main" { "setup" } else { name });
            }
            buf.push('(');
            params_str_into(sig, &mut buf);
            buf.push_str(") ");
            if let Some(b) = body {
                self.emit_block_into(b, &mut buf)?;
            } else {
                buf.push(';');
            }
            buf.push('\n');
            Ok(buf)
        } else { Ok(String::new()) }
    }

    #[allow(dead_code)]
    fn emit_block(&mut self, block: &Block) -> Result<String> {
        // Pre-size: assume ~40 bytes per statement (typical simple statement)
        let mut buf = String::with_capacity(block.stmts.len() * 40 + 8);
        self.emit_block_into(block, &mut buf)?;
        Ok(buf)
    }

    fn emit_block_into(&mut self, block: &Block, buf: &mut String) -> Result<()> {
        self.push_indent();
        buf.push_str("{\n");
        for stmt in &block.stmts {
            self.emit_stmt_into(stmt, buf)?;
        }
        self.pop_indent();
        buf.push_str(self.pad());
        buf.push('}');
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<String> {
        let mut buf = String::with_capacity(64);
        self.emit_stmt_into(stmt, &mut buf)?;
        Ok(buf)
    }

    fn emit_stmt_into(&mut self, stmt: &Stmt, buf: &mut String) -> Result<()> {
        use std::fmt::Write as W;
        let pad = self.pad();
        match stmt {
            Stmt::VarDecl { name, ty, init, .. } => {
                // Infer package type from RHS constructor call (mirrors ShortDecl logic)
                // so that  var sensor = dht.New(...)  inside a function also works.
                if ty.is_none() {
                    if let Some(init_expr) = init {
                        if let Expr::Call { func, .. } = init_expr {
                            if let Expr::Select { expr: pkg_expr, .. } = func.as_ref() {
                                if let Expr::Ident { name: pkg_alias, .. } = pkg_expr.as_ref() {
                                    if let Some(canon) = self.pkg_map.get(pkg_alias.as_str()).cloned() {
                                        self.var_types.insert(name.clone(), canon);
                                    }
                                }
                            }
                        }
                    }
                }
                let t = ty.as_ref().map(|t| t.to_cpp_str())
                    .unwrap_or(std::borrow::Cow::Borrowed("auto"));
                buf.push_str(pad);
                buf.push_str(&t);
                buf.push(' ');
                buf.push_str(name);
                if let Some(e) = init {
                    buf.push_str(" = ");
                    self.emit_expr_into(e, buf)?;
                }
                buf.push_str(";\n");
            }
            Stmt::ConstDecl { name, ty, val, .. } => {
                let t = ty.as_ref().map(|t| t.to_cpp_str())
                    .unwrap_or(std::borrow::Cow::Borrowed("auto"));
                buf.push_str(pad);
                buf.push_str("const ");
                buf.push_str(&t);
                buf.push(' ');
                buf.push_str(name);
                buf.push_str(" = ");
                self.emit_expr_into(val, buf)?;
                buf.push_str(";\n");
            }
            Stmt::ShortDecl { names, vals, .. } => {
                for (i, name) in names.iter().enumerate() {
                    // Infer package type from RHS constructor call
                    if let Some(val_node) = vals.get(i) {
                        if let Expr::Call { func, .. } = val_node {
                            if let Expr::Select { expr: pkg_expr, .. } = func.as_ref() {
                                if let Expr::Ident { name: pkg_alias, .. } = pkg_expr.as_ref() {
                                    if let Some(canon) = self.pkg_map.get(pkg_alias.as_str()).cloned() {
                                        self.var_types.insert(name.clone(), canon);
                                    }
                                }
                            }
                        }
                    }
                    buf.push_str(pad);
                    buf.push_str("auto ");
                    buf.push_str(name);
                    buf.push_str(" = ");
                    if let Some(v) = vals.get(i) {
                        self.emit_expr_into(v, buf)?;
                    } else {
                        buf.push('0');
                    }
                    buf.push_str(";\n");
                }
            }
            Stmt::Assign { lhs, rhs, op, .. } => {
                for (i, l) in lhs.iter().enumerate() {
                    buf.push_str(pad);
                    self.emit_expr_into(l, buf)?;
                    buf.push(' ');
                    buf.push_str(op.to_cpp());
                    buf.push(' ');
                    if let Some(r) = rhs.get(i) {
                        self.emit_expr_into(r, buf)?;
                    } else {
                        buf.push('0');
                    }
                    buf.push_str(";\n");
                }
            }
            Stmt::Inc { expr, .. } => {
                buf.push_str(pad);
                self.emit_expr_into(expr, buf)?;
                buf.push_str("++;\n");
            }
            Stmt::Dec { expr, .. } => {
                buf.push_str(pad);
                self.emit_expr_into(expr, buf)?;
                buf.push_str("--;\n");
            }
            Stmt::Return { vals, .. } => {
                buf.push_str(pad);
                match vals.len() {
                    0 => buf.push_str("return;\n"),
                    1 => {
                        buf.push_str("return ");
                        self.emit_expr_into(&vals[0], buf)?;
                        buf.push_str(";\n");
                    }
                    _ => {
                        buf.push_str("return { ");
                        for (i, v) in vals.iter().enumerate() {
                            if i > 0 { buf.push_str(", "); }
                            self.emit_expr_into(v, buf)?;
                        }
                        buf.push_str(" }; // multi-return\n");
                    }
                }
            }
            Stmt::If { init, cond, then, else_, .. } => {
                buf.push_str(pad);
                buf.push_str("if (");
                if let Some(i) = init {
                    let raw = self.emit_stmt(i)?;
                    buf.push_str(raw.trim().trim_end_matches(';'));
                    buf.push(' ');
                }
                self.emit_expr_into(cond, buf)?;
                buf.push_str(") ");
                self.emit_block_into(then, buf)?;
                if let Some(e) = else_ {
                    buf.push_str(" else ");
                    match e.as_ref() {
                        Stmt::If { .. } => {
                            let s = self.emit_stmt(e)?;
                            buf.push_str(s.trim_start());
                        }
                        Stmt::Block(b) => self.emit_block_into(b, buf)?,
                        other => {
                            let s = self.emit_stmt(other)?;
                            buf.push_str(s.trim());
                        }
                    }
                }
                buf.push('\n');
            }
            Stmt::For { init, cond, post, body, .. } => {
                buf.push_str(pad);
                buf.push_str("for (");
                buf.push_str(&flat_stmt_opt(init, self)?);
                buf.push_str("; ");
                if let Some(c) = cond { self.emit_expr_into(c, buf)?; }
                buf.push_str("; ");
                buf.push_str(&flat_stmt_opt(post, self)?);
                buf.push_str(") ");
                self.emit_block_into(body, buf)?;
                buf.push('\n');
            }
            Stmt::Range { key, val, iter, body, .. } => {
                let arr = self.emit_expr(iter)?;
                let k   = key.as_deref().unwrap_or("_i");
                buf.push_str(pad);
                let _ = write!(buf,
                    "for (int32_t {k} = 0; {k} < (int32_t)(sizeof({a})/sizeof({a}[0])); {k}++) ",
                    k = k, a = arr,
                );
                if let Some(vname) = val {
                    buf.push_str("{\n");
                    buf.push_str(pad);
                    buf.push_str("    auto ");
                    buf.push_str(vname);
                    buf.push_str(" = ");
                    buf.push_str(&arr);
                    buf.push('['); buf.push_str(k); buf.push_str("];\n");
                    // emit body stmts
                    self.push_indent();
                    for st in &body.stmts { self.emit_stmt_into(st, buf)?; }
                    self.pop_indent();
                    buf.push_str(pad);
                    buf.push_str("}\n");
                } else {
                    self.emit_block_into(body, buf)?;
                    buf.push('\n');
                }
            }
            Stmt::Switch { tag, cases, .. } => {
                if tag.is_none() {
                    for (idx, case) in cases.iter().enumerate() {
                        if case.exprs.is_empty() {
                            buf.push_str(" else {\n");
                        } else {
                            if idx == 0 { buf.push_str(pad); buf.push_str("if ("); }
                            else { buf.push_str(" else if ("); }
                            for (ci, e) in case.exprs.iter().enumerate() {
                                if ci > 0 { buf.push_str(" || "); }
                                self.emit_expr_into(e, buf)?;
                            }
                            buf.push_str(") {\n");
                        }
                        self.push_indent();
                        for st in &case.body { self.emit_stmt_into(st, buf)?; }
                        self.pop_indent();
                        buf.push_str(pad); buf.push('}');
                    }
                    buf.push('\n');
                } else {
                    buf.push_str(pad);
                    buf.push_str("switch (");
                    self.emit_expr_into(tag.as_ref().unwrap(), buf)?;
                    buf.push_str(") {\n");
                    self.push_indent();
                    for case in cases {
                        let cpad = self.pad();
                        if case.exprs.is_empty() {
                            buf.push_str(cpad); buf.push_str("default:\n");
                        } else {
                            for e in &case.exprs {
                                buf.push_str(cpad); buf.push_str("case ");
                                self.emit_expr_into(e, buf)?;
                                buf.push_str(":\n");
                            }
                        }
                        self.push_indent();
                        for st in &case.body { self.emit_stmt_into(st, buf)?; }
                        buf.push_str(self.pad()); buf.push_str("break;\n");
                        self.pop_indent();
                    }
                    self.pop_indent();
                    buf.push_str(pad); buf.push_str("}\n");
                }
            }
            Stmt::Block(b) => {
                buf.push_str(pad);
                self.emit_block_into(b, buf)?;
                buf.push('\n');
            }
            Stmt::Expr { expr, .. } => {
                buf.push_str(pad);
                self.emit_expr_into(expr, buf)?;
                buf.push_str(";\n");
            }
            Stmt::Break    { .. }        => { buf.push_str(pad); buf.push_str("break;\n"); }
            Stmt::Continue { .. }        => { buf.push_str(pad); buf.push_str("continue;\n"); }
            Stmt::Goto     { label, .. } => { buf.push_str(pad); buf.push_str("goto "); buf.push_str(label); buf.push_str(";\n"); }
            Stmt::Label    { name, .. }  => { buf.push_str(pad); buf.push_str(name); buf.push_str(":\n"); }
            Stmt::Defer    { call, .. }  => {
                buf.push_str(pad);
                if self.cfg.annotate_unsupported { buf.push_str("/* defer — RAII wrapper not yet emitted */ "); }
                self.emit_expr_into(call, buf)?;
                buf.push_str(";\n");
            }
            Stmt::Go       { call, .. }  => {
                buf.push_str(pad);
                if self.cfg.annotate_unsupported { buf.push_str("/* goroutine — not supported on bare metal */ "); }
                self.emit_expr_into(call, buf)?;
                buf.push_str(";\n");
            }
        }
        Ok(())
    }

    fn emit_expr(&self, expr: &Expr) -> Result<String> {
        let mut buf = String::with_capacity(32);
        self.emit_expr_into(expr, &mut buf)?;
        Ok(buf)
    }

    fn emit_expr_into(&self, expr: &Expr, buf: &mut String) -> Result<()> {
        use std::fmt::Write as W;
        match expr {
            Expr::Int(n)   => { let _ = write!(buf, "{}", n); }
            Expr::Float(f) => {
                let s = format!("{}", f);
                buf.push_str(&s);
                if !s.contains('.') { buf.push_str(".0"); }
            }
            Expr::Str(s)   => {
                // Escape to valid C++ string literal
                let start_len = buf.len();
                if self.cfg.arduino_string { buf.push_str("String(\""); }
                else { buf.push('"'); }
                for byte in s.bytes() {
                    match byte {
                        b'\\'       => buf.push_str("\\\\"),
                        b'"'        => buf.push_str("\\\""),
                        b'\n'       => buf.push_str("\\n"),
                        b'\r'       => buf.push_str("\\r"),
                        b'\t'       => buf.push_str("\\t"),
                        0x20..=0x7E => buf.push(byte as char),
                        other       => { let _ = write!(buf, "\\x{:02X}", other); }
                    }
                }
                if self.cfg.arduino_string { buf.push_str("\")"); }
                else { buf.push('"'); }
                let _ = start_len; // suppress unused warning
            }
            Expr::Rune(c)  => { let _ = write!(buf, "'{}'", c); }
            Expr::Bool(b)  => buf.push_str(if *b { "true" } else { "false" }),
            Expr::Nil      => buf.push_str("nullptr"),
            Expr::Raw(s)   => buf.push_str(s),
            Expr::Ident { name, .. } => buf.push_str(&self.resolve_ident(name)),
            Expr::Binary { op, lhs, rhs, .. } => {
                buf.push('(');
                self.emit_expr_into(lhs, buf)?;
                buf.push(' ');
                buf.push_str(op.to_cpp());
                buf.push(' ');
                self.emit_expr_into(rhs, buf)?;
                buf.push(')');
            }
            Expr::Unary { op, expr, .. } => {
                buf.push('(');
                buf.push_str(op.to_cpp());
                self.emit_expr_into(expr, buf)?;
                buf.push(')');
            }
            Expr::Call { func, args, .. } => self.emit_call_into(func, args, buf)?,
            Expr::Index { expr, idx, .. } => {
                self.emit_expr_into(expr, buf)?;
                buf.push('[');
                self.emit_expr_into(idx, buf)?;
                buf.push(']');
            }
            Expr::Slice { expr, lo, hi, .. } => {
                let a = self.emit_expr(expr)?;
                let lo_s = lo.as_ref().map(|e| self.emit_expr(e)).transpose()?
                    .unwrap_or_else(|| "0".into());
                let hi_s = hi.as_ref().map(|e| self.emit_expr(e)).transpose()?
                    .unwrap_or_else(|| format!("sizeof({})/sizeof({}[0])", a, a));
                let _ = write!(buf, "/* &{}[{}..{}] */", a, lo_s, hi_s);
            }
            Expr::Select { expr, field, .. } => {
                if let Expr::Ident { name: alias, .. } = expr.as_ref() {
                    let canon = self.pkg_map.get(alias.as_str())
                        .cloned().unwrap_or_else(|| alias.clone());
                    if let Some(pkg) = self.rt.pkg(&canon) {
                        if let Some(const_val) = pkg.constants.get(field.as_str()) {
                            buf.push_str(const_val);
                            return Ok(());
                        }
                    }
                    if self.cfg.passthrough_unknown {
                        buf.push_str(alias);
                        buf.push('.');
                        buf.push_str(field);
                        return Ok(());
                    }
                    return Err(TsukiError::codegen(format!("no mapping for {}.{}", canon, field)));
                }
                self.emit_expr_into(expr, buf)?;
                buf.push('.');
                buf.push_str(field);
            }
            Expr::TypeAssert { expr, .. } => self.emit_expr_into(expr, buf)?,
            Expr::Composite { elems, .. } => {
                buf.push('{');
                for (i, e) in elems.iter().enumerate() {
                    if i > 0 { buf.push_str(", "); }
                    self.emit_expr_into(&e.val, buf)?;
                }
                buf.push('}');
            }
            Expr::FuncLit { sig, .. } => {
                let _ = write!(buf, "[&]({}) -> {} {{ /* lambda body */ }}",
                    params_str(sig), ret_type(sig));
            }
        }
        Ok(())
    }

    #[allow(dead_code)]
    fn emit_call(&self, func: &Expr, args: &[Expr]) -> Result<String> {
        let mut buf = String::with_capacity(48);
        self.emit_call_into(func, args, &mut buf)?;
        Ok(buf)
    }

    fn emit_call_into(&self, func: &Expr, args: &[Expr], buf: &mut String) -> Result<()> {
        use std::fmt::Write as W;
        let is_printf_style = matches!(func,
            Expr::Select { field, .. }
                if matches!(field.as_str(), "Printf" | "Fprintf" | "Sprintf" | "Errorf")
        );

        // Build arg strings — reuse a Vec to avoid repeated allocs
        let mut arg_strs: Vec<String> = Vec::with_capacity(args.len());
        for (i, a) in args.iter().enumerate() {
            if is_printf_style && i == 0 {
                arg_strs.push(self.emit_str_raw(a)?);
            } else {
                arg_strs.push(self.emit_expr(a)?);
            }
        }

        match func {
            Expr::Select { expr, field, .. } => {
                if let Expr::Ident { name: alias, .. } = expr.as_ref() {
                    // ── tsuki-webkit static calls ─────────────────────────────────────
                    if let Some(canon) = self.pkg_map.get(alias.as_str()) {
                        if canon == "tsuki_webkit" {
                            match field.as_str() {
                                "ApiInit" | "WebInit" => buf.push_str("WebkitHandle{}"),
                                other => {
                                    let _ = write!(buf, "webkit_{}({})",
                                        other.to_lowercase(), arg_strs.join(", "));
                                }
                            }
                            return Ok(());
                        }
                    }
                    // ── tsuki-webkit instance method calls ────────────────────────────
                    if let Some(pkg_name) = self.var_types.get(alias.as_str()) {
                        if pkg_name == "tsuki_webkit" {
                            match field.as_str() {
                                "setup"   => buf.push_str("webkit_setup_routes()"),
                                "tick"    => buf.push_str("webkit_tick()"),
                                "LocalIP" => buf.push_str("webkit_local_ip()"),
                                "WiFi"    => { let _ = write!(buf, "webkit_wifi({})", arg_strs.join(", ")); }
                                "Handle"  => { let _ = write!(buf, "webkit_handle({})", arg_strs.join(", ")); }
                                other     => { let _ = write!(buf, "webkit_{}({})", other.to_lowercase(), arg_strs.join(", ")); }
                            }
                            return Ok(());
                        }
                    }
                    // ── Case 1: static package call ────────────────────────────────────
                    if let Some(canon) = self.pkg_map.get(alias.as_str()) {
                        if let Some(pkg) = self.rt.pkg(canon) {
                            if let Some(fmap) = pkg.functions.get(field.as_str()) {
                                fmap.apply_into(&arg_strs, buf);
                                return Ok(());
                            }
                        }
                        if self.cfg.passthrough_unknown {
                            let _ = write!(buf, "{}.{}({})", alias, field, arg_strs.join(", "));
                            return Ok(());
                        }
                        return Err(TsukiError::codegen(
                            format!("no mapping for {}.{}", canon, field)));
                    }
                    // ── Case 2: instance method call ───────────────────────────────────
                    if let Some(pkg_name) = self.var_types.get(alias.as_str()) {
                        if let Some(pkg) = self.rt.pkg(pkg_name) {
                            if let Some(fmap) = pkg.functions.get(field.as_str()) {
                                // Prepend receiver without cloning into a new Vec
                                let mut all_args = Vec::with_capacity(arg_strs.len() + 1);
                                all_args.push(alias.clone());
                                all_args.extend_from_slice(&arg_strs);
                                fmap.apply_into(&all_args, buf);
                                return Ok(());
                            }
                        }
                        if self.cfg.passthrough_unknown {
                            let _ = write!(buf, "{}.{}({})", alias, field, arg_strs.join(", "));
                            return Ok(());
                        }
                        return Err(TsukiError::codegen(
                            format!("no method mapping for {}.{} (package: {})", alias, field, pkg_name)));
                    }
                }
                // ── Chained: pkg.SubObj.Method(args) e.g. arduino.Serial.Begin(9600) ──
                if let Expr::Select { expr: inner_expr, field: sub_obj, .. } = expr.as_ref() {
                    if let Expr::Ident { name: pkg_alias, .. } = inner_expr.as_ref() {
                        if self.pkg_map.contains_key(pkg_alias.as_str()) {
                            let sub_canon = sub_obj.to_lowercase();
                            if let Some(sub_pkg) = self.rt.pkg(&sub_canon) {
                                if let Some(fmap) = sub_pkg.functions.get(field.as_str()) {
                                    fmap.apply_into(&arg_strs, buf);
                                    return Ok(());
                                }
                            }
                            if self.cfg.passthrough_unknown {
                                let _ = write!(buf, "{}.{}({})", sub_obj, field, arg_strs.join(", "));
                                return Ok(());
                            }
                            return Err(TsukiError::codegen(
                                format!("no mapping for {}.{}.{}", pkg_alias, sub_obj, field)));
                        }
                    }
                }
                let obj = self.emit_expr(expr)?;
                let _ = write!(buf, "{}.{}({})", obj, field, arg_strs.join(", "));
            }
            Expr::Ident { name, .. } => {
                if let Some(bm) = self.rt.builtin(name) {
                    bm.apply_into(&arg_strs, buf);
                } else {
                    buf.push_str(&self.resolve_ident(name));
                    buf.push('(');
                    for (i, a) in arg_strs.iter().enumerate() {
                        if i > 0 { buf.push_str(", "); }
                        buf.push_str(a);
                    }
                    buf.push(')');
                }
            }
            _ => {
                self.emit_expr_into(func, buf)?;
                buf.push('(');
                for (i, a) in arg_strs.iter().enumerate() {
                    if i > 0 { buf.push_str(", "); }
                    buf.push_str(a);
                }
                buf.push(')');
            }
        }
        Ok(())
    }

    /// Emit a string expression as a raw C-string literal (for printf format args).
    fn emit_str_raw(&self, expr: &Expr) -> Result<String> {
        if let Expr::Str(s) = expr {
            let mut out = String::with_capacity(s.len() + 2);
            out.push('"');
            for byte in s.bytes() {
                match byte {
                    b'\\'       => out.push_str("\\\\"),
                    b'"'        => out.push_str("\\\""),
                    b'\n'       => out.push_str("\\n"),
                    b'\r'       => out.push_str("\\r"),
                    b'\t'       => out.push_str("\\t"),
                    0x20..=0x7E => out.push(byte as char),
                    other       => { use std::fmt::Write as W; let _ = write!(out, "\\x{:02X}", other); }
                }
            }
            out.push('"');
            Ok(out)
        } else {
            let s = self.emit_expr(expr)?;
            if s.starts_with("String(\"") && s.ends_with("\")") {
                Ok(s[7..s.len()-1].to_owned())
            } else {
                Ok(s)
            }
        }
    }

    /// Resolve a Go identifier to its C++ equivalent.
    /// Checks the constant map for all imported packages; returns the name itself on miss.
    #[inline]
    fn resolve_ident(&self, name: &str) -> String {
        // Fast path: check arduino package constants first (most common case)
        if let Some(arduino) = self.rt.pkg("arduino") {
            if let Some(cpp) = arduino.constants.get(name) {
                return cpp.clone();
            }
        }
        // Slow path: check all other packages
        for canon in self.pkg_map.values() {
            if canon == "arduino" { continue; } // already checked
            if let Some(pkg) = self.rt.pkg(canon) {
                if let Some(cpp) = pkg.constants.get(name) {
                    return cpp.clone();
                }
            }
        }
        name.to_owned()
    }
} // impl Transpiler

// ─────────────────────────────────────────────────────────────────────────────
//  Signature helpers — write into a buffer to avoid per-call allocations
// ─────────────────────────────────────────────────────────────────────────────

fn params_str_into(sig: &FuncSig, buf: &mut String) {
    for (i, p) in sig.params.iter().enumerate() {
        if i > 0 { buf.push_str(", "); }
        if p.variadic {
            buf.push_str(".../* ");
            buf.push_str(&p.ty.to_cpp());
            buf.push_str(" */");
        } else {
            buf.push_str(&p.ty.to_cpp());
            buf.push(' ');
            match p.name.as_deref() {
                Some(n) if !n.is_empty() => buf.push_str(n),
                _ => { buf.push_str("_p"); buf.push_str(&i.to_string()); }
            }
        }
    }
}

fn params_str(sig: &FuncSig) -> String {
    let cap = sig.params.len() * 12;
    let mut buf = String::with_capacity(cap);
    params_str_into(sig, &mut buf);
    buf
}

fn ret_type_into(sig: &FuncSig, buf: &mut String) {
    match sig.results.len() {
        0 => buf.push_str("void"),
        1 => buf.push_str(&sig.results[0].ty.to_cpp()),
        _ => {
            buf.push_str("/* multi: ");
            for (i, r) in sig.results.iter().enumerate() {
                if i > 0 { buf.push_str(", "); }
                buf.push_str(&r.ty.to_cpp());
            }
            buf.push_str(" */");
        }
    }
}

fn ret_type(sig: &FuncSig) -> String {
    let mut buf = String::with_capacity(8);
    ret_type_into(sig, &mut buf);
    buf
}

fn flat_stmt_opt(stmt: &Option<Box<Stmt>>, t: &mut Transpiler) -> Result<String> {
    Ok(match stmt {
        None    => String::new(),
        Some(s) => {
            let raw = t.emit_stmt(s)?;
            raw.trim().trim_end_matches(';').to_string()
        }
    })
}