[board]
id             = "pro_mini_3v3"
name           = "Arduino Pro Mini 3.3V"
version        = "1.0.0"
fqbn           = "arduino:avr:pro:cpu=8MHzatmega328"
variant        = "eightanaloginputs"
flash_kb       = 32
ram_kb         = 2
toolchain_type = "avr"
defines        = "ARDUINO_AVR_PRO,ARDUINO_ARCH_AVR"

[avr]
mcu        = "atmega328p"
f_cpu      = 8000000
programmer = "arduino"
baud       = 57600
