[board]
id          = "lolin_d1_mini"
name        = "Lolin Wemos D1 Mini"
fqbn        = "esp8266:esp8266:d1_mini"
variant     = "d1_mini"
flash_kb    = 4096
ram_kb      = 80
description = "Lolin (Wemos) D1 Mini — ESP8266, WiFi, 4MB flash (Lolin brand alias)"
author      = "tsuki-team"
version     = "1.0.0"

[toolchain]
type        = "esp8266"

[defines]
values = ["ARDUINO_ESP8266_WEMOS_D1MINI", "ARDUINO_ARCH_ESP8266", "ESP8266"]
