[board]
id          = "nano_old"
name        = "Arduino Nano (old bootloader)"
fqbn        = "arduino:avr:nano:cpu=atmega328old"
variant     = "eightanaloginputs"
flash_kb    = 32
ram_kb      = 2
description = "Arduino Nano with old optiboot bootloader — baud 57600"
author      = "tsuki-team"
version     = "1.0.0"

[toolchain]
type        = "avr"
mcu         = "atmega328p"
f_cpu       = 16000000
programmer  = "arduino"
baud        = 57600

[defines]
values = ["ARDUINO_AVR_NANO", "ARDUINO_ARCH_AVR"]
