// ─────────────────────────────────────────────────────────────────────────────
//  tsuki :: python :: transpiler
//
//  Converts a PyProgram (Python AST) → Arduino C++ source string.
//
//  Package mapping reuses the same Runtime as the Go transpiler, so all
//  tsukilib packages work transparently with Python source files.
// ─────────────────────────────────────────────────────────────────────────────

use std::collections::{HashMap, HashSet};
use std::fmt::Write as FmtWrite;

use crate::error::{Result, TsukiError};
use crate::runtime::Runtime;
use crate::transpiler::TranspileConfig;
use super::ast::*;

// ── Transpiler struct ─────────────────────────────────────────────────────────

pub struct PyTranspiler {
    cfg:      TranspileConfig,
    rt:       Runtime,
    indent:   usize,
    includes: HashSet<String>,
    /// Which Python module names are imported (e.g. "arduino", "time", "fmt")
    imports:  HashSet<String>,
    /// Maps module alias → canonical name (from `import foo as f`)
    aliases:  HashMap<String, String>,
    /// Inferred variable types: name → C++ type string
    var_types: HashMap<String, String>,
}

impl PyTranspiler {
    pub fn new(cfg: TranspileConfig, rt: Runtime) -> Self {
        Self {
            cfg,
            rt,
            indent:    0,
            includes:  HashSet::with_capacity(8),
            imports:   HashSet::with_capacity(8),
            aliases:   HashMap::with_capacity(4),
            var_types: HashMap::with_capacity(16),
        }
    }

    // ── Entry point ───────────────────────────────────────────────────────────

    pub fn generate(&mut self, prog: &PyProgram) -> Result<String> {
        // Register imports
        for imp in &prog.imports {
            let _canon = imp.alias.as_deref().map(|_| imp.module.as_str()).unwrap_or(&imp.module);
            let name = imp.module.split('.').next().unwrap_or(&imp.module).to_owned();
            self.imports.insert(name.clone());
            if let Some(alias) = &imp.alias {
                self.aliases.insert(alias.clone(), imp.module.clone());
            }
            // Register include from runtime if available
            if let Some(pkg) = self.rt.packages.get(&name) {
                if let Some(h) = &pkg.header {
                    self.includes.insert(h.clone());
                }
            }
            // Also check `from foo import bar` names
            for item in &imp.names {
                let fq = format!("{}.{}", imp.module, item);
                if let Some(pkg) = self.rt.packages.get(&fq) {
                    if let Some(h) = &pkg.header {
                        self.includes.insert(h.clone());
                    }
                }
            }
        }
        self.includes.insert("Arduino.h".into());

        // Two-pass: collect variable types from globals first
        for stmt in &prog.globals {
            self.infer_var_type_stmt(stmt);
        }

        // ── Build output ──────────────────────────────────────────────────────
        // Pre-allocate: Python C++ output is ~3-4x the source size
        let mut out = String::with_capacity(prog.globals.len() * 40
            + prog.functions.len() * 200 + 256);

        // Header comment
        let _ = write!(out,
            "// Generated by tsuki (Python -> C++) - board: {}\n// DO NOT EDIT - edit the .py source instead\n\n",
            self.cfg.board
        );

        // Includes — sort into a temp Vec (avoids cloning all strings)
        let mut incs: Vec<&String> = self.includes.iter().collect();
        incs.sort_unstable();
        for i in incs { let _ = writeln!(out, "#include <{}>", i); }
        out.push('\n');

        // Globals
        for stmt in &prog.globals {
            out += &self.emit_stmt(stmt)?;
        }
        if !prog.globals.is_empty() { out += "\n"; }

        // Forward declarations (non-setup/loop functions)
        for f in &prog.functions {
            if f.name != "setup" && f.name != "loop" {
                out += &self.emit_func_fwd(f)?;
            }
        }
        if prog.functions.iter().any(|f| f.name != "setup" && f.name != "loop") {
            out += "\n";
        }

        // Functions — setup/loop go last (Arduino convention)
        let mut ordered: Vec<&PyFuncDef> = prog.functions.iter()
            .filter(|f| f.name != "setup" && f.name != "loop")
            .collect();
        if let Some(s) = prog.functions.iter().find(|f| f.name == "setup") { ordered.push(s); }
        if let Some(l) = prog.functions.iter().find(|f| f.name == "loop")  { ordered.push(l); }

        for f in ordered {
            out += &self.emit_func(f)?;
        }

        Ok(out)
    }

    // ── Forward declaration ───────────────────────────────────────────────────

    fn emit_func_fwd(&self, f: &PyFuncDef) -> Result<String> {
        let ret = self.py_type_to_cpp(f.return_type.as_deref().unwrap_or("void"));
        let params = self.emit_params(&f.params)?;
        Ok(format!("{} {}({});\n", ret, f.name, params))
    }

    // ── Function emission ─────────────────────────────────────────────────────

    fn emit_func(&mut self, f: &PyFuncDef) -> Result<String> {
        let ret = self.py_type_to_cpp(f.return_type.as_deref().unwrap_or("void"));
        let params = self.emit_params(&f.params)?;
        let mut out = format!("{} {}({}) {{\n", ret, f.name, params);
        self.indent += 1;
        for stmt in &f.body {
            out += &self.emit_stmt(stmt)?;
        }
        self.indent -= 1;
        out += "}\n\n";
        Ok(out)
    }

    fn emit_params(&self, params: &[PyParam]) -> Result<String> {
        let mut buf = String::with_capacity(params.len() * 10);
        for (i, p) in params.iter().enumerate() {
            if i > 0 { buf.push_str(", "); }
            let ty = self.py_type_to_cpp(p.ann.as_deref().unwrap_or("auto"));
            buf.push_str(ty.as_ref());
            buf.push(' ');
            buf.push_str(&p.name);
        }
        Ok(buf)
    }

    // ── Statement emission ────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &PyStmt) -> Result<String> {
        // Static pad lookup — zero allocation for common indent depths
        const PADS: [&str; 9] = ["","    ","        ","            ","                ",
            "                    ","                        ","                            ",
            "                                "];
        let ind = PADS.get(self.indent).copied().unwrap_or("");
        match stmt {
            PyStmt::Comment(c) => Ok(format!("{}// {}\n", ind, c)),

            PyStmt::Pass(_) => Ok(format!("{}/* pass */\n", ind)),

            PyStmt::Break(_) => Ok(format!("{}break;\n", ind)),

            PyStmt::Continue(_) => Ok(format!("{}continue;\n", ind)),

            PyStmt::Global { names, .. } => {
                // In C++ globals are already global — emit a comment
                Ok(format!("{}// global: {}\n", ind, names.join(", ")))
            }

            PyStmt::Return { value, .. } => {
                match value {
                    None    => Ok(format!("{}return;\n", ind)),
                    Some(e) => Ok(format!("{}return {};\n", ind, self.emit_expr(e)?)),
                }
            }

            PyStmt::Assign { target, ann, value, .. } => {
                let cpp_type = ann.as_deref()
                    .map(|a| self.py_type_to_cpp(a).into_owned())
                    .or_else(|| {
                        // Infer type from value
                        value.as_ref().map(|v| self.infer_expr_type(v))
                    });

                match (cpp_type, value) {
                    (Some(ty), Some(v)) => {
                        let val = self.emit_expr(v)?;
                        // Store type for later use
                        self.var_types.insert(target.clone(), ty.clone());
                        // Detect stack-allocated constructor call: ClassName(args)
                        // emitted as idiomatic `ClassName varname(args)` instead of
                        // `ClassName varname = ClassName(args)`.
                        let ctor_prefix = format!("{}(", ty);
                        if val.starts_with(&ctor_prefix) && val.ends_with(')') && !ty.ends_with('*') {
                            let inner = &val[ctor_prefix.len()..val.len()-1];
                            Ok(format!("{}{} {}({});\n", ind, ty, target, inner))
                        } else {
                            Ok(format!("{}{} {} = {};\n", ind, ty, target, val))
                        }
                    }
                    (None, Some(v)) => {
                        let val = self.emit_expr(v)?;
                        Ok(format!("{}auto {} = {};\n", ind, target, val))
                    }
                    (Some(ty), None) => {
                        self.var_types.insert(target.clone(), ty.clone());
                        Ok(format!("{}{} {};\n", ind, ty, target))
                    }
                    (None, None) => {
                        Ok(format!("{}/* {} */\n", ind, target))
                    }
                }
            }

            PyStmt::AugAssign { target, op, value, .. } => {
                let val = self.emit_expr(value)?;
                let op_str = op.to_cpp();
                Ok(format!("{}{} {}= {};\n", ind, target, op_str, val))
            }

            PyStmt::Expr(e) => {
                let s = self.emit_expr(e)?;
                Ok(format!("{}{};\n", ind, s))
            }

            PyStmt::If { cond, body, elif_clauses, else_body, .. } => {
                let mut out = format!("{}if ({}) {{\n", ind, self.emit_expr(cond)?);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}", ind);

                for (ec, eb) in elif_clauses {
                    out += &format!(" else if ({}) {{\n", self.emit_expr(ec)?);
                    self.indent += 1;
                    for s in eb { out += &self.emit_stmt(s)?; }
                    self.indent -= 1;
                    out += &format!("{}}}", ind);
                }

                if !else_body.is_empty() {
                    out += " else {\n";
                    self.indent += 1;
                    for s in else_body { out += &self.emit_stmt(s)?; }
                    self.indent -= 1;
                    out += &format!("{}}}", ind);
                }
                out += "\n";
                Ok(out)
            }

            PyStmt::While { cond, body, .. } => {
                let mut out = format!("{}while ({}) {{\n", ind, self.emit_expr(cond)?);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}\n", ind);
                Ok(out)
            }

            PyStmt::For { var, iter, body, .. } => {
                let for_header = self.emit_for_header(var, iter)?;
                let mut out = format!("{}{} {{\n", ind, for_header);
                self.indent += 1;
                for s in body { out += &self.emit_stmt(s)?; }
                self.indent -= 1;
                out += &format!("{}}}\n", ind);
                Ok(out)
            }
        }
    }

    /// Emit the `for (...)` header for Python `for var in iter`.
    fn emit_for_header(&mut self, var: &str, iter: &PyExpr) -> Result<String> {
        // Detect `range(n)`, `range(a, b)`, `range(a, b, step)`
        if let PyExpr::Call { func, args, .. } = iter {
            let fname = self.flatten_expr_name(func);
            if fname == "range" {
                return match args.len() {
                    1 => {
                        let end = self.emit_expr(&args[0])?;
                        Ok(format!("for (int {} = 0; {} < {}; {}++)", var, var, end, var))
                    }
                    2 => {
                        let start = self.emit_expr(&args[0])?;
                        let end   = self.emit_expr(&args[1])?;
                        Ok(format!("for (int {} = {}; {} < {}; {}++)", var, start, var, end, var))
                    }
                    3 => {
                        let start = self.emit_expr(&args[0])?;
                        let end   = self.emit_expr(&args[1])?;
                        let step  = self.emit_expr(&args[2])?;
                        Ok(format!("for (int {} = {}; {} < {}; {} += {})", var, start, var, end, var, step))
                    }
                    _ => Err(TsukiError::Codegen("range() takes 1-3 arguments".into())),
                };
            }
            // enumerate(iterable) — simplified, just iterate with index
            if fname == "enumerate" && !args.is_empty() {
                let iter_expr = self.emit_expr(&args[0])?;
                return Ok(format!(
                    "for (size_t {} = 0; {} < sizeof({}) / sizeof({}[0]); {}++)",
                    var, var, iter_expr, iter_expr, var
                ));
            }
        }

        // Fallback: range-based for over array/pointer
        let iter_s = self.emit_expr(iter)?;
        Ok(format!("for (auto {} : {})", var, iter_s))
    }

    /// Extract a dotted name from an expression (for function name detection).
    fn flatten_expr_name(&self, expr: &PyExpr) -> String {
        match expr {
            PyExpr::Ident(s) => s.clone(),
            PyExpr::Attr { obj, attr, .. } => {
                let mut s = self.flatten_expr_name(obj);
                s.push('.');
                s.push_str(attr);
                s
            }
            _ => String::new(),
        }
    }

    // ── Expression emission ───────────────────────────────────────────────────

    pub fn emit_expr(&mut self, expr: &PyExpr) -> Result<String> {
        match expr {
            PyExpr::Int(v)   => Ok(v.to_string()),
            PyExpr::Float(v) => {
                let s = format!("{}", v);
                // Ensure C++ recognizes it as a float literal
                if s.contains('.') { Ok(s) } else { Ok(format!("{}.0", s)) }
            }
            PyExpr::Bool(b)  => Ok(if *b { "true" } else { "false" }.into()),
            PyExpr::None     => Ok("NULL".into()),
            PyExpr::Str(s)   => Ok(format!("\"{}\"", s.replace('"', "\\\""))),
            PyExpr::Ident(s) => Ok(self.resolve_ident(s)),
            PyExpr::List(elems) => {
                let parts: Result<Vec<_>> = elems.iter().map(|e| self.emit_expr(e)).collect();
                Ok(format!("{{{}}}", parts?.join(", ")))
            }

            PyExpr::Attr { obj, attr, .. } => {
                let obj_name = self.flatten_expr_name(obj);
                // Check if it's a package constant (e.g. arduino.HIGH, arduino.OUTPUT)
                let resolved_mod = self.resolve_module(&obj_name);
                if let Some(pkg) = self.rt.packages.get(&resolved_mod) {
                    if let Some(c) = pkg.constants.get(attr.as_str()) {
                        return Ok(c.clone());
                    }
                }
                // Default: obj.attr → obj.attr
                let obj_s = self.emit_expr(obj)?;
                Ok(format!("{}.{}", obj_s, attr))
            }

            PyExpr::Call { func, args, .. } => self.emit_call(func, args),

            PyExpr::Subscript { obj, index, .. } => {
                let o = self.emit_expr(obj)?;
                let i = self.emit_expr(index)?;
                Ok(format!("{}[{}]", o, i))
            }

            PyExpr::BinOp { left, op, right, .. } => {
                // Special-case ** (pow) → pow(left, right)
                if *op == BinOp::Pow {
                    let l = self.emit_expr(left)?;
                    let r = self.emit_expr(right)?;
                    self.includes.insert("math.h".into());
                    return Ok(format!("pow({}, {})", l, r));
                }
                let l = self.emit_expr(left)?;
                let r = self.emit_expr(right)?;
                Ok(format!("({} {} {})", l, op.to_cpp(), r))
            }

            PyExpr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand)?;
                let op_str = match op {
                    UnaryOp::Not    => "!",
                    UnaryOp::Neg    => "-",
                    UnaryOp::BitNot => "~",
                };
                Ok(format!("({}{})", op_str, o))
            }

            PyExpr::FStr { parts, .. } => {
                // Simplified f-string → snprintf style
                let mut fmt_str = String::new();
                let mut fmt_args = Vec::new();
                for part in parts {
                    match part {
                        FStrPart::Literal(s) => fmt_str.push_str(s),
                        FStrPart::Expr(e) => {
                            fmt_str.push_str("%s");
                            fmt_args.push(format!("String({})", self.emit_expr(e)?));
                        }
                    }
                }
                if fmt_args.is_empty() {
                    Ok(format!("\"{}\"", fmt_str))
                } else {
                    Ok(format!(
                        "([&]({{ char _b[256]; snprintf(_b, sizeof(_b), \"{}\", {}); return String(_b); }})())",
                        fmt_str,
                        fmt_args.join(", ")
                    ))
                }
            }
        }
    }

    // ── Call dispatch ─────────────────────────────────────────────────────────

    fn emit_call(&mut self, func: &PyExpr, args: &[PyExpr]) -> Result<String> {
        let fname = self.flatten_expr_name(func);

        // ── Built-in Python functions ─────────────────────────────────────────
        match fname.as_str() {
            "print" => {
                // print(x) → Serial.println(x)
                // print(x, end="") → Serial.print(x)
                let args_s: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                let args_s = args_s?;
                if args_s.len() == 1 {
                    return Ok(format!("Serial.println({})", args_s[0]));
                }
                return Ok(format!("Serial.print({})", args_s.join(", ")));
            }
            "len" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("(sizeof({}) / sizeof({}[0]))", s, s));
                }
            }
            "int" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((int)({}))", s));
                }
            }
            "float" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((float)({}))", s));
                }
            }
            "str" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("String({})", s));
                }
            }
            "bool" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("((bool)({}))", s));
                }
            }
            "abs" => {
                if let Some(a) = args.first() {
                    let s = self.emit_expr(a)?;
                    return Ok(format!("abs({})", s));
                }
            }
            "min" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("min({})", parts?.join(", ")));
            }
            "max" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("max({})", parts?.join(", ")));
            }
            "map" | "constrain" => {
                let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
                return Ok(format!("{}({})", fname, parts?.join(", ")));
            }
            _ => {}
        }

        // ── Module-qualified call: pkg.Func(args) ─────────────────────────────
        // We must extract everything we need from `self.rt` *before* calling
        // `self.emit_expr`, because emit_expr takes `&mut self` and the borrow
        // checker would otherwise see a simultaneous shared borrow on `self.rt`
        // and a mutable borrow on `self`.
        if let Some(dot) = fname.find('.') {
            let mod_name = &fname[..dot];
            let fn_name  = &fname[dot+1..];
            let resolved = self.resolve_module(mod_name);

            // --- Phase 1: immutable snapshot from rt (borrow ends at end of block)
            let maybe_fn_map_and_header: Option<(crate::runtime::FnMap, Option<String>)> =
                self.rt.packages.get(&resolved).and_then(|pkg| {
                    pkg.functions.get(fn_name)
                        .map(|fm| (fm.clone(), pkg.header.clone()))
                });

            let maybe_constant: Option<String> =
                if maybe_fn_map_and_header.is_none() {
                    self.rt.packages.get(&resolved)
                        .and_then(|pkg| pkg.constants.get(fn_name).cloned())
                } else {
                    None
                };

            // --- Phase 2: use &mut self freely now that the rt borrow is gone
            if let Some((fn_map, header)) = maybe_fn_map_and_header {
                let cpp_args: Vec<String> = args.iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Result<Vec<_>>>()?;
                if let Some(h) = header {
                    self.includes.insert(h);
                }
                return Ok(fn_map.apply(&cpp_args));
            }
            if let Some(c) = maybe_constant {
                return Ok(c);
            }
        }

        // ── Fallback: emit as-is ──────────────────────────────────────────────
        // Before giving up entirely, check if mod_name is a typed local variable
        // whose type maps to a known package (instance method call).
        // Example: sensor.read_temperature() where sensor : DHT*
        //   → var_types["sensor"] = "DHT*"  (set by constructor call inference)
        //   → find package with cpp_class == "DHT"
        //   → look up fn_name = "read_temperature" in that package
        //   → apply template with receiver = "sensor" as {0}
        if let Some(dot) = fname.find('.') {
            let mod_name = &fname[..dot];
            let fn_name  = &fname[dot+1..];

            // Guard: if mod_name is itself a loaded package name, this is a
            // module-qualified call (e.g. `dht.new(...)`) that already failed
            // the package lookup above (package not installed / not in
            // pkg_names).  Do NOT fall into the instance-method path — doing
            // so would match a stale var_types entry for a package alias and
            // apply a completely wrong C++ template, or worse, bubble up
            // through the final fallback and emit `new DHT(...)` via the
            // runtime builtin "new" → "(new {0}())" mapping.
            let mod_is_package = self.rt.packages.contains_key(mod_name);

            if !mod_is_package {
            if let Some(cpp_type) = self.var_types.get(mod_name).cloned() {
                let base_type = cpp_type.trim_end_matches('*').to_owned();

                // Phase 1: immutable snapshot — find the matching package
                let snapshot: Option<(crate::runtime::FnMap, Option<String>)> =
                    self.rt.packages.values()
                        .find(|p| p.cpp_class.as_deref() == Some(&base_type))
                        .and_then(|p| p.functions.get(fn_name).map(|fm| (fm.clone(), p.header.clone())));

                // Phase 2: use &mut self freely
                if let Some((fn_map, header)) = snapshot {
                    // Receiver is {0}; user-visible args start at {1}
                    let mut cpp_args = vec![mod_name.to_owned()];
                    cpp_args.extend(
                        args.iter()
                            .map(|a| self.emit_expr(a))
                            .collect::<Result<Vec<_>>>()?
                    );
                    if let Some(h) = header { self.includes.insert(h); }
                    return Ok(fn_map.apply(&cpp_args));
                }
            }
            } // end !mod_is_package guard
        }

        let parts: Result<Vec<_>> = args.iter().map(|a| self.emit_expr(a)).collect();
        let func_s = self.emit_expr(func)?;
        Ok(format!("{}({})", func_s, parts?.join(", ")))
    }

    // ── Name resolution ───────────────────────────────────────────────────────

    /// Resolve a Python identifier to its C++ equivalent.
    fn resolve_ident(&self, name: &str) -> String {
        // Fast path: arduino constants are by far the most common (HIGH, LOW, etc.)
        if self.imports.contains("arduino") {
            if let Some(pkg) = self.rt.packages.get("arduino") {
                if let Some(c) = pkg.constants.get(name) {
                    return c.clone();
                }
            }
        }
        // Slow path: all other imported packages
        for mod_name in &self.imports {
            if mod_name == "arduino" { continue; }
            if let Some(pkg) = self.rt.packages.get(mod_name.as_str()) {
                if let Some(c) = pkg.constants.get(name) {
                    return c.clone();
                }
            }
        }
        name.to_owned()
    }

    /// Resolve a module name through aliases.
    fn resolve_module(&self, name: &str) -> String {
        self.aliases.get(name).cloned().unwrap_or_else(|| name.to_owned())
    }

    // ── Type system ───────────────────────────────────────────────────────────

    /// Convert a Python type annotation to a C++ type string.
    fn py_type_to_cpp(&self, ann: &str) -> std::borrow::Cow<'static, str> {
        use std::borrow::Cow::*;
        match ann {
            "int"           => Borrowed("int"),
            "float"         => Borrowed("float"),
            "bool"          => Borrowed("bool"),
            "str"           => if self.cfg.arduino_string { Borrowed("String") } else { Borrowed("const char*") },
            "bytes"         => Borrowed("uint8_t*"),
            "None" | "void" => Borrowed("void"),
            "auto"          => Borrowed("auto"),
            "int8"          => Borrowed("int8_t"),
            "int16"         => Borrowed("int16_t"),
            "int32"         => Borrowed("int32_t"),
            "int64"         => Borrowed("int64_t"),
            "uint8"         => Borrowed("uint8_t"),
            "uint16"        => Borrowed("uint16_t"),
            "uint32"        => Borrowed("uint32_t"),
            "uint64"        => Borrowed("uint64_t"),
            "byte"          => Borrowed("byte"),
            "word"          => Borrowed("word"),
            "double"        => Borrowed("double"),
            "long"          => Borrowed("long"),
            "unsigned_long" => Borrowed("unsigned long"),
            "char"          => Borrowed("char"),
            "size_t"        => Borrowed("size_t"),
            other           => Owned(other.to_owned()),
        }
    }

    /// Infer a C++ type from an expression (best-effort).
    fn infer_expr_type(&self, expr: &PyExpr) -> String {
        match expr {
            PyExpr::Int(_)   => "int".to_owned(),
            PyExpr::Float(_) => "float".to_owned(),
            PyExpr::Bool(_)  => "bool".to_owned(),
            PyExpr::Str(_)   => if self.cfg.arduino_string { "String".to_owned() } else { "const char*".to_owned() },
            PyExpr::Ident(n) => self.var_types.get(n).cloned().unwrap_or_else(|| "auto".to_owned()),
            // Constructor call: pkg.new(…) / pkg.New(…)
            // If the package has a cpp_class, the variable type is `ClassName`
            // (stack-allocated; method templates use `{0}.method()`).
            //
            // IMPORTANT: if the package is NOT loaded we must still return
            // "auto" here via the explicit early return below.  Without it,
            // the emit_call final fallback can reach the builtin `new` entry
            // (FnMap::template("(new {0})")) and emit `new DHT(...)` instead
            // of a proper error or placeholder.
            PyExpr::Call { func, .. } => {
                let fname = self.flatten_expr_name(func);
                if let Some(dot) = fname.find('.') {
                    let mod_name = &fname[..dot];
                    let fn_name  = &fname[dot+1..];
                    if fn_name == "new" || fn_name == "New" {
                        let resolved = self.resolve_module(mod_name);
                        if let Some(pkg) = self.rt.packages.get(&resolved) {
                            if let Some(class) = &pkg.cpp_class {
                                // Determine whether the constructor template allocates on
                                // the heap (produces `new ClassName(...)`) or the stack
                                // (produces `ClassName(...)`).
                                //
                                // Heap packages: cpp = "new DHT({0},{1})"
                                //   → method templates use {0}->method()
                                //   → variable type must be ClassName* (pointer)
                                //
                                // Stack packages: cpp = "DHT({0},{1})"
                                //   → method templates use {0}.method()
                                //   → variable type is ClassName (value)
                                //
                                // We detect this by probing the constructor template:
                                // apply it with empty dummy args and check whether the
                                // result starts with "new ".
                                let is_heap = pkg.functions.get("new")
                                    .or_else(|| pkg.functions.get("New"))
                                    .map(|fm| {
                                        let probe = fm.apply(&[
                                            String::new(), String::new(),
                                            String::new(), String::new(),
                                        ]);
                                        probe.trim_start().starts_with("new ")
                                    })
                                    .unwrap_or(false);
                                if is_heap {
                                    return format!("{}*", class);
                                } else {
                                    return class.clone();
                                }
                            }
                        }
                        // Package not loaded or has no cpp_class: return "auto"
                        // immediately so we never accidentally reach the builtin
                        // `new` → `(new {0}())` path in the call emitter.
                        return "auto".into();
                    }
                }
                "auto".into()
            }
            _ => "auto".into(),
        }
    }

    /// Pre-pass: collect variable types from assignment statements.
    fn infer_var_type_stmt(&mut self, stmt: &PyStmt) {
        if let PyStmt::Assign { target, ann, value, .. } = stmt {
            let ty = ann.as_deref()
                .map(|a| self.py_type_to_cpp(a).into_owned())
                .or_else(|| value.as_ref().map(|v| self.infer_expr_type(v)));
            if let Some(t) = ty {
                self.var_types.insert(target.clone(), t);
            }
        }
    }
}