[board]
id          = "mega"
name        = "Arduino Mega 2560"
fqbn        = "arduino:avr:mega"
variant     = "mega"
flash_kb    = 256
ram_kb      = 8
description = "Arduino Mega 2560 — AVR ATmega2560, 54 digital I/O, 256K flash"
author      = "tsuki-team"
version     = "1.0.0"

[toolchain]
type        = "avr"
mcu         = "atmega2560"
f_cpu       = 16000000
programmer  = "wiring"
baud        = 115200

[defines]
values = ["ARDUINO_AVR_MEGA2560", "ARDUINO_ARCH_AVR"]
