[board]
id             = "leonardo"
name           = "Arduino Leonardo"
version        = "1.0.0"
fqbn           = "arduino:avr:leonardo"
variant        = "leonardo"
flash_kb       = 32
ram_kb         = 2
toolchain_type = "avr"
defines        = "ARDUINO_AVR_LEONARDO,ARDUINO_ARCH_AVR,USB_VID=0x2341,USB_PID=0x0036"

[avr]
mcu        = "atmega32u4"
f_cpu      = 16000000
programmer = "avr109"
baud       = 57600
