[board]
id             = "d1_mini"
name           = "Wemos D1 Mini"
version        = "1.0.0"
fqbn           = "esp8266:esp8266:d1_mini"
variant        = "d1_mini"
flash_kb       = 4096
ram_kb         = 80
toolchain_type = "esp8266"
defines        = "ARDUINO_ESP8266_WEMOS_D1MINI,ARDUINO_ARCH_ESP8266,ESP8266"

[esp8266]
f_cpu = 80000000
